# Generated by Django 4.1.5 on 2023-01-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя бренда')),
                ('img_brend', models.ImageField(upload_to='brend/', verbose_name='Фирменное изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
                ('img_categoriya', models.ImageField(blank=True, null=True, upload_to='catgeoriya/', verbose_name='Изображение категории')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
