# Generated by Django 4.1.5 on 2023-02-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
