# Generated by Django 4.1.5 on 2023-01-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0002_advantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='img',
            field=models.FileField(upload_to='Advantages/'),
        ),
    ]
