# Generated by Django 4.1.5 on 2023-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriya',
            name='img_categoriya',
            field=models.FileField(blank=True, null=True, upload_to='catgeoriya/', verbose_name='Изображение категории'),
        ),
    ]
