# Generated by Django 4.1.5 on 2023-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0006_alter_product_amunt_alter_seocontent_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOMap',
        ),
        migrations.AlterField(
            model_name='product',
            name='amunt',
            field=models.CharField(blank=True, default='618954011', max_length=250, null=True),
        ),
    ]
