# Generated by Django 4.1.5 on 2023-01-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0006_alter_product_atrikul'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('pochta', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_admin_panel.product')),
            ],
        ),
    ]
