# Generated by Django 4.1.5 on 2023-02-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0007_delete_seomap_alter_product_amunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amunt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
