# Generated by Django 4.1.5 on 2023-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0008_alter_product_amunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img_brend',
            field=models.FileField(upload_to='brend/', verbose_name='Фирменное изображение'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='img',
            field=models.FileField(upload_to='delivery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='product/'),
        ),
    ]
