# Generated by Django 4.1.5 on 2023-01-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0008_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='prodcut/def.png', upload_to='product/'),
        ),
    ]
