# Generated by Django 4.1.5 on 2023-03-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0009_alter_brand_img_brend_alter_delivery_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriya',
            name='urls',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
