# Generated by Django 4.1.5 on 2023-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0010_categoriya_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
