# Generated by Django 4.1.5 on 2023-01-30 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0011_alter_product_amunt_alter_product_atrikul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorsiya_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_admin_panel.categoriya'),
        ),
    ]
