# Generated by Django 4.1.5 on 2023-01-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0012_alter_product_categorsiya_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brend_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_admin_panel.brand'),
        ),
    ]
