# Generated by Django 4.1.5 on 2023-02-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_admin_panel', '0021_product_img_url_product_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_url',
            new_name='img_urls',
        ),
    ]
